### ISSUE TITLE
Improve Performance

### ISSUE THREAD

**Issue by mahyarx** [invictus-ir/Microsoft-365-Extractor-Suite#2]
@invictus-ir , @anthonybm 
If adding code below after line 177, you can get much better performance 
because when halving the internal in a loop it can get into very short interval like 7.5min and there will be times out of peak where in 7.5min won't be too much logs but steps still on that interval, and since making connection and retrieving logs takes more than few seconds so better the same way as we halved interval reverting by doubling 

    if($script:integer -lt $(get-random -Minimum 2500 -Maximum 4500)){

        $IntervalMinutes = [INT]$IntervalMinutes + [INT]$(get-random -Minimum $($IntervalMinutes/1.25) -Maximum $IntervalMinutes)
        $CurrentEnd = $CurrentStart.AddMinutes($IntervalMinutes)
        write-host "INFO: Temporary increasing time interval to $IntervalMinutes minutes" -ForegroundColor Yellow
    }

**Comment by invictus-ir** [comment]
Hi can you please create a pull request not sure if this is for the light or for the full version. I'd happy to try it.
